#!/bin/bash
FFSC=$(zenity --list --radiolist --title="FFS Font and Keyboard Switcher" --text="System font and keyboard is" --column="Check:" --column="Font Name:" TRUE "Myanmar3" FALSE "Zawgyi2009")

if [[ $FFSC == *"Zawgyi2009"* ]]
then
	ffs z
	notify-send -u critical -t 500 Zawgyi Zawyi2009 -i zawgyi

    else	
	ffs u
	notify-send -u critical -t 500 Unicode Myanmar3 -i unicode
fi
